---
extends: default

rules:
  line-length:
    max: 120
    allow-non-breakable-words: true
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
  comments:
    min-spaces-from-content: 1
  document-start: disable
  comments-indentation: disable

ignore: |
  .venv/
  .git/
  node_modules/
  .github/ISSUE_TEMPLATE/*.yml
